[SCALA-131] with filter vs filter example
Baeldung/scala-tutorials pull request #232
Opened 2020-09-29 17:45 UTC by ldrygala

2020-09-30 07:50 UTC, ashleyfrieze requested changes

2020-09-30 07:50 UTC, ashleyfrieze commented on scala-core-3/src/main/scala/com/baeldung/scala/withfilter/WithFilterVsFilter.scala
> +      println("get name" + programmer)
Do we want to use console output here? or should we be using unit tests to demonstrate what the code does?

2020-09-30 07:50 UTC, ashleyfrieze commented on scala-core-3/src/main/scala/com/baeldung/scala/withfilter/WithFilterVsFilter.scala
> +  val knowMoreThan1Language: Programmer => Boolean =
Should be `knows` rather than `know`. The programmer is singular so he or she _knows_

2020-09-30 07:50 UTC, ashleyfrieze commented on scala-core-3/src/main/scala/com/baeldung/scala/withfilter/WithFilterVsFilter.scala
> +    .map(getName)
Better I think to have these as methods which unit tests can call to assert the right answers.

2020-10-02 11:38 UTC, lor6 commented
retest this please

2020-10-02 11:43 UTC, lor6 commented
retest this please

2020-10-20 07:56 UTC, ashleyfrieze commented
retest this please

2020-10-21 08:08 UTC, ashleyfrieze commented
retest this please

2020-10-21 17:34 UTC, merged